### PR TITLE
WIP: developer environment with pip "editable" mode

### PR DESCRIPTION
**Pull request by avinson**

### CODE REVIEW

**Comment by avinson** [comment]
background is that we want to use pip "editable" mode via `pip install -e` but currently repos are not structured correctly for this. instead of a `src/` directory, the name should match the name of the module to be imported like:
```
my_project
|-- README
|-- my_package
|-- |-- __init__.py
|-- |-- my_subpackage
```
follow the [20180115-avinson-pip-editable](https://github.com/probcomp/bayeslite/tree/20180115-avinson-pip-editable) branch in bayeslite for corresponding work. currently, there are just a few symlinks created as workarounds but the repo structure may need to be changed more significantly. currently, import of bayeslite in editable mode fails with `20180115-avinson-pip-editable`.

steps to reproduce:
- check out `probcomp/developer` repo with 20180115-avinson-pip-editable branch
- docker-compose run --rm notebook
- import bayeslite twice
```
In [1]: import bayeslite
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0ae61ea1c848> in <module>()
----> 1 import bayeslite

/home/jovyan/bayeslite/bayeslite/__init__.py in <module>()
     54 """
     55
---> 56 from bayeslite.bayesdb import BayesDB
     57 from bayeslite.bayesdb import bayesdb_open
     58 from bayeslite.bayesdb import IBayesDBTracer

/home/jovyan/bayeslite/bayeslite/bayesdb.py in <module>()
     24 import bayeslite.bqlfn as bqlfn
     25 import bayeslite.bqlvtab as bqlvtab
---> 26 import bayeslite.parse as parse
     27 import bayeslite.schema as schema
     28 import bayeslite.txn as txn

/home/jovyan/bayeslite/bayeslite/parse.py in <module>()
     20
     21 import bayeslite.ast as ast
---> 22 import bayeslite.grammar as grammar
     23 import bayeslite.scan as scan
     24 from bayeslite.exception import BQLParseError

ImportError: No module named grammar

In [2]: import bayeslite
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0ae61ea1c848> in <module>()
----> 1 import bayeslite

/home/jovyan/bayeslite/bayeslite/__init__.py in <module>()
     54 """
     55
---> 56 from bayeslite.bayesdb import BayesDB
     57 from bayeslite.bayesdb import bayesdb_open
     58 from bayeslite.bayesdb import IBayesDBTracer

/home/jovyan/bayeslite/bayeslite/bayesdb.py in <module>()
     21 import struct
     22
---> 23 import bayeslite.bql as bql
     24 import bayeslite.bqlfn as bqlfn
     25 import bayeslite.bqlvtab as bqlvtab

AttributeError: 'module' object has no attribute 'bql'

In [3]:
```

additional info, one of the conda core devs recommends using `pip install -e` over `conda develop`: https://github.com/conda/conda-build/issues/1990#issuecomment-305549938

**Comment by fsaad** [comment]
1. Are you sure that `pip install -e .` requires the source directory to have the same name as the python project? I would be surprised if this was a hard constraint; please check the documentation as there might be a way around this via the `package_dir` kwarg in `setup` from `setup.py`. Any change to repo structures should be very carefully planned and discussed.

2. More generally, pip editable mode is unlikely to be workable for developing in our repositories (aside from cgpm). As far as I understand, pip editable is similar `python setup.py develop` which is makes it "convenient" for a developer to edit code without having to write `python setup.py build` on a per-change basis by creating symlinks/eggs to raw source. However for almost all our projects, `python setup.py build` does in fact need to be run after each generic edit. The `setup.py` file contains auxiliary non-python commands, such as generating the grammar in bayeslite, cythonizing the .pyx files recompiling C++ source in crosscat, reinstalling .js artifacts for iventure, and many subroutines happening Venturecxx. The `./pythenv.sh` script that exists in each repo is designed to address this issue.

**Comment by avinson** [comment]
@fsaad it still sounds like it might be desirable to support edit-in-place for certain repos (perhaps not venturecxx). you would only need to regenerate the grammar files and re-cythonize if you were specifically developing on those parts of the source, correct? This is really up to the active developers and not me but always having to run a build process after any edit (regardless of necessity) seems a bit cumbersome.

**Comment by fsaad** [comment]
> This is really up to the active developers and not me but always having to run a build process after any edit (regardless of necessity) seems a bit cumbersome.

I agree it may seem a bit cumbersome in principle, but over time I have found that given the nature of repositories (all aside from cgpm, which is pure python) the most robust and least bug-prone way to develop, and certainly the one we should encourage, is to explicitly rebuild (using either `python setup.py build` with `pythenv.sh` or using `pip install .`) and always rely on `./check.sh` to run tests for the edits.

For developers who wish to work around the suggested best practice, the standard approach is to just set an environment variable and create a soft link, as follows:
```
$ echo export PYTHONPATH=${PYTHONPATH}:/path/to/bayeslite >> /path/to/venv/bin/activate
$ ln -s /path/to/bayeslite/src /path/to/bayeslite/bayeslite
```
Creating the softlink in line #2 also would allow `python setup.py develop` or `pip install -e .` to be happy with regard to matching names.

As a developer, I do not believe it is worth investing any significant engineering time or resources in getting `pip editable` or `python setup.py develop` and supporting this use-case across our repos given the brittleness it will cause.

**Pull request closed without merging**
